### ISSUE TITLE
Related issues of training

### ISSUE THREAD

**Issue by vhzy** [ZebangCheng/Emotion-LLaMA#31]
作者您好，感谢你们开源工作，我自己训练模型后发现无法复现您best_checkpoint的结果，因此有几个问题想要咨询您：
1.关于task_pool的选择，根据您的readme，stage1选择emotion和reason，stage2选择reason_v2，对应现在版本的代码，应该是stage1选择emotion和reason，stage2选择infer吗？
2.stage2应该使用stage1的哪个checkpoint？根据EmotionLLaMA/checkpoints/save_checkpoint/stage2/log.txt，您选择第七个checkpoint，readme写的是29个epoch，实际应该如何选择呢？
3.训练和测试的image_path是test3的视频数据即可吗？
4.论文中训练iter写的是训练300,000 steps，实际应该训练30*1000=30000个steps？这里是一个typo吗？
期待您的回复！

**Comment by ZebangCheng** [comment]
1.reason_v2相关部分已上传。感谢提醒。
2.readme中应该写的是，选择分数较高的checkpoint进行下一个阶段。为了方便，可以直接选用最后一个checkpoint。
3.“训练和测试的image_path是test3的视频数据即可吗？”这个问题不是很清楚？MER2023的训练集路径和测试集路径是一样的：
```
train:
    image_path: /home/user/big_space/datasets/Emotion/MER2023/video
    ann_path: /home/user/big_space/datasets/Emotion/MER2023/all_label_NCEV.txt
    
test:
    eval_file_path: /home/user/big_space/datasets/Emotion/MER2023/relative_test3_NCEV.txt # MER2023
    img_path: /home/user/big_space/datasets/Emotion/MER2023/video
```
4.300,000 steps 是估算的。300,000 steps = 30 epochs * 5000 iters_per_epoch * 2 (stages)
